import moment from 'moment'

export const peripheralRiskColumns = {
  1: [
    { label: '列入原因', key: 'putReason' },
    { label: '列入时间', key: 'putDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '决定列入部门', key: 'putDepartment' },
    { label: '移除原因', key: 'removeReason' },
    { label: '移除时间', key: 'removeDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '决定移除部门', key: 'removeDepartment' },
  ],
  3: [
    { label: '失信公司', key: 'iname' },
    { label: '法定代表人', key: 'businessentity' },
    { label: '执行依据文号', key: 'gistid' },
    { label: '省份', key: 'areaname' },
    { label: '身份证号／组织机构代码', key: 'cardnum' },
    { label: '执行法院', key: 'courtname' },
    { label: '失信人类型，0代表人，1代表公司', key: 'type' },
    { label: '发布时间', key: 'publishdate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '做出执行依据单位', key: 'gistunit' },
    { label: '法律生效文书确定的义务', key: 'duty', width: 500 },
    { label: '被执行人的履行情况', key: 'performance' },
    { label: '立案时间', key: 'regdate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '失信被执行人行为具体情形', key: 'disrupttypename' },
    { label: '案号', key: 'casecode' },
  ],
  5: [
    { label: '被执行人名称', key: 'pname' },
    { label: '执行法院', key: 'execCourtName' },
    { label: '身份证号／组织机构代码', key: 'partyCardNum' },
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '执行标的', key: 'execMoney' },
  ],
  6: [
    { label: '行政处罚内容', key: 'content', width: 500 },
    { label: '行政处罚决定书文号', key: 'punishNumber' },
    { label: '注册号', key: 'regNum' },
    { label: '名称', key: 'name' },
    { label: '省份', key: 'base' },
    { label: '作出行政处罚决定日期', key: 'decisionDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '法定代表人（负责人）姓名', key: 'legalPersonName' },
    { label: '违法行为类型', key: 'type', width: 500 },
    { label: '作出行政处罚决定机关名称', key: 'departmentName' },
    { label: '公示日期', key: 'publishDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '描述', key: 'description' },
  ],
  7: [
    { label: '创建时间', key: 'gmtCreate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '列入时间', key: 'putDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '移除时间', key: 'removeDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '决定移除部门', key: 'removeDepartment' },
    { label: '移除原因', key: 'removeReason' },
    { label: '决定列入部门', key: 'putDepartment' },
    { label: '列入原因', key: 'putReason' },
  ],
  8: [
    { label: '标题', key: 'title' },
    { label: '提交时间', key: 'submittime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '法院', key: 'court' },
    { label: '案件类型', key: 'casetype' },
    { label: '文书类型', key: 'doctype' },
    { label: '代理人', key: 'agent' },
    { label: '原文链接地址', key: 'url' },
    { label: '案件号', key: 'caseno' },
  ],
  9: [
    { label: '出质股权数额', key: 'equityAmount' },
    { label: '登记编号', key: 'regNumber' },
    { label: '质权人', key: 'pledgee' },
    { label: '股权出质设立发布日期', key: 'putDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '股权出质设立登记日期', key: 'regDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '省份简称', key: 'base' },
    { label: '状态', key: 'state' },
    { label: '出质人', key: 'pledgor' },
    { label: '质权人证照/证件号码', key: 'certifNumberR' },
    { label: '出质人证照/证件号码', key: 'certifNumber' },
    { label: '变化情况', key: 'changeSituation' },
    { label: '注销日期', key: 'cancelDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '注销原因', key: 'cancel' },
  ],
  10: [
    { label: '被担保债权数额', key: 'amount' },
    { label: '担保范围', key: 'scope' },
    { label: '概况债务人履行债务的期限', key: 'overviewTerm' },
    { label: '登记机关', key: 'regDepartment' },
    { label: '备注', key: 'remark' },
    // { label: '内部使用', key: 'businessId' },
    { label: '状态', key: 'status' },
    { label: '登记编号', key: 'regNum' },
    { label: '登记日期', key: 'regDate' },
    { label: '省份简称', key: 'base' },
    { label: '被担保债权种类', key: 'type' },
    { label: '公示日期', key: 'publishDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '债务人履行债务的期限', key: 'term' },
    { label: '概况种类', key: 'overviewType' },
    { label: '概况数额', key: 'overviewAmount' },
    { label: '概况担保的范围', key: 'overviewScope' },
    { label: '概况备注', key: 'overviewRemark' },
    { label: '注销日期', key: 'cancelDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '注销原因', key: 'cancelReason' },
  ],
  11: [
    { label: '证件号码', key: 'personIdNumber' },
    { label: '经营地点', key: 'location' },
    { label: '纳税人类型', key: 'taxpayerType' },
    { label: '发布日期', key: 'publishDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '法人或负责人名称', key: 'legalpersonName' },
    { label: '欠税金额', key: 'ownTaxAmount' },
    { label: '税款所属税务机关', key: 'department' },
    { label: '纳税人识别号', key: 'taxIdNumber' },
    { label: '欠税税种', key: 'taxCategory' },
    { label: '当前新发生欠税余额', key: 'newOwnTaxBalance' },
    { label: '纳税人名称', key: 'name' },
    { label: '欠税余额', key: 'ownTaxBalance' },
    { label: '法人证件名称', key: 'personIdName' },
    { label: '税务类型:0国税，1地税', key: 'TYPE' },
  ],
  12: [
    { label: '创建时间', key: 'createTime' },
    { label: '变更事项', key: 'changeItem' },
    { label: '变更前', key: 'contentBefore' },
    { label: '变更后', key: 'contentAfter' },
    { label: '变更日期', key: 'changeTime' },
  ],
  13: [
    { label: '开庭日期(时间)', key: 'startDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '审判长/主审人', key: 'judge' },
    { label: '法庭', key: 'courtroom' },
    { label: '法院', key: 'court' },
    { label: '承办部门', key: 'contractors' },
    { label: '当事人', key: 'litigant' },
    { label: '案由', key: 'casereason' },
  ],
  14: [
    { label: '公告类型名称', key: 'bltntypename' },
    { label: '法院名', key: 'courtcode' },
    { label: '刊登日期', key: 'publishdate' },
    { label: '案件内容', key: 'content', width: 500 },
    { label: '手机号', key: 'mobilephone' },
    { label: '刊登版面', key: 'publishpage' },
    { label: '原告', key: 'party1' },
    { label: '当事人', key: 'party2' },
    { label: '省份', key: 'province' },
    { label: '公告号', key: 'bltnno' },
  ],
  15: [
    { label: '创建时间', key: 'createTime' },
    { label: '变更事项', key: 'changeItem' },
    { label: '变更前', key: 'contentBefore' },
    { label: '变更后', key: 'contentAfter' },
    { label: '变更日期', key: 'changeTime' },
  ],
  16: [
    { label: '创建时间', key: 'createTime' },
    { label: '变更事项', key: 'changeItem' },
    { label: '变更前', key: 'contentBefore' },
    { label: '变更后', key: 'contentAfter' },
    { label: '变更日期', key: 'changeTime' },
  ],
  17: [
    { label: '创建时间', key: 'createTime' },
    { label: '变更事项', key: 'changeItem' },
    { label: '变更前', key: 'contentBefore' },
    { label: '变更后', key: 'contentAfter' },
    { label: '变更日期', key: 'changeTime' },
  ],
  18: [
    { label: '创建时间', key: 'createTime' },
    { label: '变更事项', key: 'changeItem' },
    { label: '变更前', key: 'contentBefore' },
    { label: '变更后', key: 'contentAfter' },
    { label: '变更日期', key: 'changeTime' },
  ],
  19: [
    { label: '创建时间', key: 'createTime' },
    { label: '变更事项', key: 'changeItem' },
    { label: '变更前', key: 'contentBefore' },
    { label: '变更后', key: 'contentAfter' },
    { label: '变更日期', key: 'changeTime' },
  ],
  20: [
    { label: '创建时间', key: 'createTime' },
    { label: '变更事项', key: 'changeItem' },
    { label: '变更前', key: 'contentBefore' },
    { label: '变更后', key: 'contentAfter' },
    { label: '变更日期', key: 'changeTime' },
  ],
  21: [
    { label: '股权数额', key: 'equityAmount' },
    { label: '类型', key: 'typeState' },
    { label: '被执行人', key: 'executedPerson' },
    { label: '执行法院', key: 'executiveCourt' },
    { label: '执行通知书文号', key: 'executeNoticeNum' },
  ],
  22: [
    { label: '清算成员名称', key: 'member' },
    { label: '清算组负责人', key: 'manager' },
  ],
  23: [
    { label: '质权人名称', key: 'pledgeeName' },
    { label: '质权登记期限', key: 'pledgeRegPeriod' },
    { label: '质权人类型1-公司2-人', key: 'pledgeeType' },
    { label: '出质人类型1-公司2-人', key: 'pledgorType' },
    { label: '种类', key: 'iprType' },
    { label: '名称', key: 'iprName' },
    { label: '知识产权登记证号', key: 'iprCertificateNum' },
    { label: '状态', key: 'state' },
    { label: '出质人名称', key: 'pledgorName' },
  ],
  24: [
    { label: '决定文书号', key: 'punish_number' },
    { label: '执法依据', key: 'punish_basis' },
    { label: '处罚单位', key: 'punish_department' },
    { label: '处罚时间', key: 'publish_time', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    // { label: '执法依据', key: 'businessId' },
    { label: '违反法律', key: 'lawbreaking' },
    { label: '违法行为', key: 'punish_reason' },
    { label: '执行情况', key: 'execution' },
    { label: '执法措施', key: 'punish_content' },
  ],
  25: [
    { label: '公告内容', key: 'infoDetail', width: 500 },
    { label: '票据类型', key: 'billType' },
    { label: '处理类型', key: 'exigentType' },
    { label: '票面金额', key: 'billAmt' },
    { label: '出票人', key: 'drawCompanyName' },
    { label: '票据号', key: 'billNum' },
    { label: '持票人', key: 'ownerCompanyName' },
    { label: '付款银行', key: 'payCompanyName' },
    { label: '出票日', key: 'billBeginDt', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '公告日期', key: 'publishDt', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '申请人', key: 'applyCompanyName' },
    { label: '公告法院', key: 'publishOrgName' }
  ],
  26: [
    { label: '公告内容', key: 'content', width: 500 },
    { label: '发布日期', key: 'startDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '公告名称', key: 'title' },
    { label: '法院', key: 'court' },
  ],
  27: [
    { label: '案件类型', key: 'caseType' },
    { label: '案件状态', key: 'caseStatus' },
    { label: '承办部门', key: 'department' },
    { label: '法院', key: 'court' },
    { label: '源链接', key: 'sourceUrl' },
    { label: '当事人', key: 'litigant' },
    { label: '开庭日期', key: 'startTime' },
    { label: '承办法官', key: 'judge' },
    { label: '地区', key: 'area' },
    { label: '法官助理', key: 'assistant' },
    { label: '案号', key: 'caseNo' },
    { label: '被告/被上诉人', key: 'defendant' },
    { label: '结案时间', key: 'closeDate' },
    { label: '原告/上诉人', key: 'plaintiff' },
    { label: '案由', key: 'caseReason' },
    { label: '立案时间', key: 'filingDate', render: (row, val) => { return val ? moment(parseFloat(val)).format('yyyy-MM-DD') : '-' } },
    { label: '第三人', key: 'third' },
    { label: '公告内容', key: 'content', width: 500 },
    { label: '来源', key: 'source' },
  ],
  28: [
    { label: '公布时间', key: 'publish_time' },
    { label: '所属税务机关', key: 'department' },
    { label: '纳税人名称', key: 'taxpayer_name' },
    { label: '案件性质', key: 'case_type' },
  ],
  29: [
    { label: '公布时间', key: 'pub_time' },
    { label: '标题名称', key: 'title' },
    { label: '法院', key: 'court' },
    { label: '拍卖起止时间', key: 'scopeDate' },
    { label: '简介', key: 'introduction' },
    { label: '公告url', key: 'url' },
  ],
  30: [
    { label: '土地座落', key: 'land_loc' },
    { label: '土地抵押登记起始时间', key: 'startDate' },
    { label: '土地抵押登记结束时间', key: 'endDate' },
    { label: '抵押面积(公顷)', key: 'mortgageArea' },
    { label: '所在行政区', key: 'landAministrativeArea' },
    { label: '抵押土地用途', key: 'mortgageToUser' },
  ],
  31: [
    { label: '登记机关', key: 'reg_authority', render: (row, val) => { return row.announcement.reg_authority ? row.announcement.reg_authority : '-' } },
    { label: '企业名称', key: 'company_name', render: (row, val) => { return row.announcement.company_name ? row.announcement.company_name : '-' } },
    { label: '统一社会信用代码/注册号', key: 'credit_code', render: (row, val) => { return row.announcement.credit_code ? row.announcement.credit_code : '-' } },
    { label: '公告期', key: 'announcement_term', render: (row, val) => { return row.announcement.announcement_term ? row.announcement.announcement_term : '-' } },
    { label: '结束日期', key: 'announcement_end_date', render: (row, val) => { return row.announcement.announcement_end_date ? row.announcement.announcement_end_date : '-' } },
    { label: '承诺书地址', key: 'ossPath', render: (row, val) => { return row.announcement.ossPath ? row.announcement.ossPath : '-' } },
  ],
  32: [
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '类型 1-公司 2-人', key: 'qyinfoType' },
  ],
  33: [
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '类型 1-公司 2-人', key: 'qyinfoType' },
  ],
  34: [
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '终本日期', key: 'caseFinalTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '执行法院', key: 'execCourtName' },
    { label: '执行标的', key: 'execMoney' },
  ],
  35: [
    { label: '出质股权数额', key: 'equityAmount' },
    { label: '质权人', key: 'pledgee' },
    { label: '登记编号', key: 'regNumber' },
    { label: '股权出质设立发布日期', key: 'putDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '股权出质设立登记日期', key: 'regDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '状态', key: 'state' },
    { label: '出质人', key: 'pledgor' },
    { label: '质权人证照/证件号码', key: 'certifNumberR' },
    { label: '出质人证照/证件号码', key: 'certifNumber' },
  ],
  36: [
    { label: '被执行人', key: 'executedPerson' },
    { label: '执行通知书文号', key: 'executeNoticeNum' },
    { label: '股权数额', key: 'equityAmount' },
    { label: '类型|状态', key: 'typeState' },
    { label: '执行人类型，2-人，1-公司', key: 'executedPersonType' },
    { label: '执行法院', key: 'executiveCourt' },
  ],
  37: [
    { label: '开始日期', key: 'startDate' },
    { label: '剩余质押股数（股）', key: 'pledgeAmount' },
    { label: '状态', key: 'status' },
    { label: '占所持股份比例', key: 'proOfSelf' },
    { label: '近期质押单位', key: 'lastkeyUnit' },
    { label: '公布日期', key: 'annDate' },
    { label: '股票单位', key: 'pledgeAmountUnit' },
    { label: '股东', key: 'shareHolder' },
    { label: '质押日收盘单位', key: 'dayClosePosUnit' },
  ],
  43: [
    { label: '开庭日期(时间)', key: 'startDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '法庭', key: 'courtroom' },
    { label: '案由', key: 'caseReason' },
    { label: '法院', key: 'court' },
    { label: '当事人', key: 'litigant' },
    { label: '案号', key: 'caseNo' },
    { label: '审判长/主审人', key: 'judge' },
  ],
  44: [
    { label: '原因', key: 'reason' },
    { label: '公告类型名称', key: 'bltntypename' },
    { label: '法院名', key: 'courtcode' },
    { label: '刊登日期', key: 'publishdate' },
    { label: '案件号', key: 'caseno' },
    { label: '案件内容', key: 'content', width: 500 },
    { label: '刊登版面', key: 'publishpage' },
    { label: '原告', key: 'party1' },
    { label: '当事人', key: 'party2' },
    { label: '省份', key: 'province' },
    { label: '公告号', key: 'bltnno' },
  ],
  46: [
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '终本日期', key: 'caseFinalTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '执行法院', key: 'execCourtName' },
    { label: '执行标的', key: 'execMoney' },
  ],
  // 行政处罚_历史
  70: [
    { label: '行政处罚内容', key: 'content', width: 500 },
    { label: '行政处罚决定书文号', key: 'punishNumber' },
    { label: '注册号', key: 'regNum' },
    { label: '名称', key: 'name' },
    { label: '省份', key: 'base' },
    { label: '作出行政处罚决定日期', key: 'decisionDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '法定代表人（负责人）姓名', key: 'legalPersonName' },
    { label: '违法行为类型', key: 'type' },
    { label: '作出行政处罚决定机关名称', key: 'departmentName' },
    { label: '公示日期', key: 'publishDate', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '描述', key: 'description' },
  ],
  // 被执行人_历史
  72: [
    { label: '被执行人名称', key: 'pname' },
    { label: '执行法院', key: 'execCourtName' },
    { label: '身份证号／组织机构代码', key: 'partyCardNum' },
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '执行标的', key: 'execMoney' },
  ],
  // 限制消费令_历史
  73: [
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '类型 1-公司 2-人', key: 'qyinfoType' },
  ],
  // 终本案件_历史
  74: [
    { label: '案号', key: 'caseCode' },
    { label: '立案时间', key: 'caseCreateTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '终本日期', key: 'caseFinalTime', render: (row, val) => { return val ? moment(val).format('yyyy-MM-DD') : '-' } },
    { label: '执行法院', key: 'execCourtName' },
    { label: '执行标的', key: 'execMoney' },
  ],
  // 经营异常_历史
  76: [
    { label: '创建时间', key: 'createTime' },
    { label: '列入时间', key: 'putDate' },
    { label: '移除时间', key: 'removeDate' },
    { label: '决定移除部门', key: 'removeDepartment' },
    { label: '移除原因', key: 'removeReason' },
    { label: '决定列入部门', key: 'putDepartment' },
    { label: '列入原因', key: 'putReason' },
  ],
}
